version: "3.7"
services:
  spring_dev_db:
    container_name: spring_dev_db
    image: "postgres:12"
    ports:
      - "5434:5432"
    volumes:
      - spring_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
volumes:
  spring_dev_data: {}
networks:
  monitoring: